language: cpp
os: linux
dist: bionic
compiler: gcc
cache:
  directories:
    - vendor/cmake-2.8.12
install:
  # vendor/cmake-2.8.12 will be created even if there's nothing in the cache, preventing the build.
  # if empty, delete it
  - rmdir --ignore-fail-on-non-empty vendor/cmake-2.8.12
  - env cmake_ver=2.8.12 ./vendor/fetch_prerequisites.sh --cmake
  - env cmake_ver=3.20.0 ./vendor/fetch_prerequisites.sh --cmake
  - ./vendor/fetch_prerequisites.sh --ittapi
  - env tracy_ver=0.7.2 ./vendor/fetch_prerequisites.sh --tracy
  - env tracy_ver=0.7.6 ./vendor/fetch_prerequisites.sh --tracy
script:
  - env cmake_ver=2.8.12 tracy_ver=0.7.2 ./tests/integration-tests.sh
  - env cmake_ver=3.20.0 tracy_ver=0.7.6 ./tests/integration-tests.sh
