#!/bin/bash

PRETTY=
test -t 1 && PRETTY=pretty

has_unbuffer() {
    command -v unbuffer >/dev/null 2>&1
}

now_ms() {
    date +%s.%3N
}

elapsed_time() {
    bc -q <<< "scale=1; ($2 - $1 + 0.05) * 10 / 10"
}

QUIET=

while [[ $# -gt 0 ]]; do
    case $1 in
    -q)
        QUIET=y
        shift
        ;;
    *)
        break
        ;;
    esac
done

command -v shell-quote >/dev/null 2>&1 && quoted_command=$(shell-quote "$@") || quoted_command="${@@Q}"

time_start=$(now_ms)
echo "[STARTED] $quoted_command"

if [ "$QUIET" = y ]; then
    TMPFILE=$(mktemp) || exit 1
    trap 'rm -f "$TMPFILE"' EXIT

    if [ -n "$PRETTY" -a has_unbuffer ]; then
        unbuffer "$@" &> "$TMPFILE"
    else
        "$@" &> "$TMPFILE"
    fi
    status=$?

    if [ $status -ne 0 ]; then
        cat "$TMPFILE"
    fi
else
    "$@"
    status=$?
fi

time_end=$(now_ms)

if [ $status -eq 0 ]; then
    echo "[SUCCESS] $quoted_command [$(elapsed_time $time_start $time_end)s]"
else
    echo "[FAILED] $quoted_command [$(elapsed_time $time_start $time_end)s]"
fi

exit $status
