name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            compiler: gcc10
          - os: ubuntu-22.04
            compiler: gcc11
          - os: ubuntu-22.04
            compiler: clang13
          - os: ubuntu-22.04
            compiler: clang14
          - os: ubuntu-22.04
            compiler: clang15
          - os: ubuntu-24.04
            compiler: gcc12
          - os: ubuntu-24.04
            compiler: gcc13
          - os: ubuntu-24.04
            compiler: gcc14
          - os: ubuntu-24.04
            compiler: clang16
          - os: ubuntu-24.04
            compiler: clang17
          - os: ubuntu-24.04
            compiler: clang18

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '23'

    - name: Enable compiler
      run: |
        case ${{ matrix.compiler }} in
          gcc10)
            echo CC=gcc-10 >> "$GITHUB_ENV"
            echo CXX=g++-10 >> "$GITHUB_ENV"
            ;;
          gcc11)
            echo CC=gcc-11 >> "$GITHUB_ENV"
            echo CXX=g++-11 >> "$GITHUB_ENV"
            ;;
          gcc12)
            echo CC=gcc-12 >> "$GITHUB_ENV"
            echo CXX=g++-12 >> "$GITHUB_ENV"
            ;;
          gcc13)
            echo CC=gcc-13 >> "$GITHUB_ENV"
            echo CXX=g++-13 >> "$GITHUB_ENV"
            ;;
          gcc14)
            echo CC=gcc-14 >> "$GITHUB_ENV"
            echo CXX=g++-14 >> "$GITHUB_ENV"
            ;;
          clang13)
            echo CC=clang-13 >> "$GITHUB_ENV"
            echo CXX=clang++-13 >> "$GITHUB_ENV"
            ;;
          clang14)
            echo CC=clang-14 >> "$GITHUB_ENV"
            echo CXX=clang++-14 >> "$GITHUB_ENV"
            ;;
          clang15)
            echo CC=clang-15 >> "$GITHUB_ENV"
            echo CXX=clang++-15 >> "$GITHUB_ENV"
            ;;
          clang16)
            echo CC=clang-16 >> "$GITHUB_ENV"
            echo CXX=clang++-16 >> "$GITHUB_ENV"
            ;;
          clang17)
            echo CC=clang-17 >> "$GITHUB_ENV"
            echo CXX=clang++-17 >> "$GITHUB_ENV"
            ;;
          clang18)
            echo CC=clang-18 >> "$GITHUB_ENV"
            echo CXX=clang++-18 >> "$GITHUB_ENV"
            ;;
        esac

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ matrix.os }}-${{ matrix.compiler }}

    - name: Install node modules
      run: npm i --progress=false

    - name: Run eslint
      run: npm run lint

    - name: Cache ittapi
      id: cache-ittapi
      uses: actions/cache@v3
      with:
        path: vendor/ittapi-3.25.5
        key: ${{ matrix.os }}-${{ matrix.compiler }}-ittapi-3.25.5

    - name: Cache tracy
      id: cache-tracy
      uses: actions/cache@v3
      with:
        path: vendor/tracy-0.11.1
        key: ${{ matrix.os }}-${{ matrix.compiler }}-tracy-0.11.1

    - name: Cache google-benchmark
      id: cache-google-benchmark
      uses: actions/cache@v3
      with:
        path: vendor/google-benchmark-1.9.1
        key: ${{ matrix.os }}-${{ matrix.compiler }}-google-benchmark-1.9.1

    - name: Configure and build
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        node bootstrap.ts ci
