name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        compiler: [gcc9, gcc10, gcc11, clang12, clang13, clang14]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Enable compiler
      run: |
        case ${{ matrix.compiler }} in
          gcc9)
            echo CC=gcc-9 >> "$GITHUB_ENV"
            echo CXX=g++-9 >> "$GITHUB_ENV"
            ;;
          gcc10)
            echo CC=gcc-10 >> "$GITHUB_ENV"
            echo CXX=g++-10 >> "$GITHUB_ENV"
            ;;
          gcc11)
            echo CC=gcc-11 >> "$GITHUB_ENV"
            echo CXX=g++-11 >> "$GITHUB_ENV"
            ;;
          clang12)
            echo CC=clang-12 >> "$GITHUB_ENV"
            echo CXX=clang++-12 >> "$GITHUB_ENV"
            ;;
          clang13)
            echo CC=clang-13 >> "$GITHUB_ENV"
            echo CXX=clang++-13 >> "$GITHUB_ENV"
            ;;
          clang14)
            echo CC=clang-14 >> "$GITHUB_ENV"
            echo CXX=clang++-14 >> "$GITHUB_ENV"
            ;;
        esac

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ matrix.os }}-${{ matrix.compiler }}

    - name: Install node modules
      run: npm i --production --progress=false

    - name: Cache ittapi
      id: cache-ittapi
      uses: actions/cache@v3
      with:
        path: vendor/ittapi-8cd2618
        key: ${{ matrix.os }}-${{ matrix.compiler }}-ittapi-8cd2618

    - name: Cache tracy
      id: cache-tracy
      uses: actions/cache@v3
      with:
        path: vendor/tracy-0.7.6
        key: ${{ matrix.os }}-${{ matrix.compiler }}-tracy-0.7.6

    - name: Cache google-benchmark
      id: cache-google-benchmark
      uses: actions/cache@v3
      with:
        path: vendor/google-benchmark-1.5.3
        key: ${{ matrix.os }}-${{ matrix.compiler }}-google-benchmark-1.5.3

    - name: Configure and build
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        node bootstrap.js ci
