name: CI

on:
  push:
    branches: [ $default-branch, dev ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1

    - name: Install node modules
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm i --production

    - name: Cache ittapi
      id: cache-ittapi
      uses: actions/cache@v2
      with:
        path: vendor/ittapi-8cd2618
        key: ${{ matrix.os }}-ittapi-8cd2618

    - name: Install ittapi
      if: steps.cache-ittapi.outputs.cache-hit != 'true'
      run: node bootstrap.js fetch-ittapi

    - name: Cache tracy
      id: cache-tracy
      uses: actions/cache@v2
      with:
        path: vendor/tracy-0.7.6
        key: ${{ matrix.os }}-tracy-0.7.6

    - name: Install tracy
      if: steps.cache-tracy.outputs.cache-hit != 'true'
      run: node bootstrap.js fetch-tracy

    - name: Cache google-benchmark
      id: cache-google-benchmark
      uses: actions/cache@v2
      with:
        path: vendor/google-benchmark-1.5.3
        key: ${{ matrix.os }}-google-benchmark-1.5.3

    - name: Install google benchmark
      if: steps.cache-google-benchmark.outputs.cache-hit != 'true'
      run: node bootstrap.js fetch-google-benchmark

    - name: Configure and build
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        node bootstrap.js configure --with-ittapi --with-tracy --with-benchmarks --build

    - name: Run tests
      run: env -C build/ ctest

    - name: Integration tests
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        node bootstrap.js integration-tests
